POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1kpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NTUwOTY3MjMsImlhdCI6MTc1NTAxMDMyMywidXNlcl9pZCI6MX0.RNFO7u2I5ZZ_o6pgz2OhY9oFDpKak8jjz8k47AVBUuY

{
    "name": "Event 3",
    "description": "Description 2",
    "date_time": "2021-01-01T00:00:00Z",
    "location": "Location 2"
}