POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQHRlc3QuY29tIiwiZXhwIjoxNzU1MzQxMDIzLCJpYXQiOjE3NTUyNTQ2MjMsInVzZXJfaWQiOjJ9.v89CHD80WnVne196vjj2irMwMjVOL4k7Yv7bfxeFe_8

{
    "name": "Event 5",
    "description": "Description 5",
    "date_time": "2021-01-01T00:00:00Z",
    "location": "Location 5"
}